name = "video-call-app"

main = "worker.js"

compatibility_date = "2026-09-08"

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
head_sampling_rate = 1
persist = true

[observability]
enabled = false


# ============================================================
# STATIC ASSETS
# ============================================================

[assets]

# Your index.html, style.css and app.js
# are currently in the project root.
directory = "."

# Allows worker.js to serve static files.
binding = "ASSETS"

# API requests go through worker.js.
# Normal static files are served directly by Cloudflare.
run_worker_first = ["/api/*"]



